// Supabase Edge Function — LIVE teach-back grader (grade-teachback).
// GENERATED by tools/gen_edge_function.py from tools/grade_teachback.py — DO NOT EDIT BY HAND.
// The quiz shell calls this on teach-back submit to show instant accuracy/spelling/punctuation lights.
// SECURITY: the ANTHROPIC_API_KEY lives here (Supabase secret) — a public page must never carry it.
// The nightly Python grader stays authoritative for the mastery ledger; this drives the instant display,
// and because both use the same prompt the lights the kid sees match the mastery signal.

const SYSTEM = `You grade a student's TEACH-BACK: their attempt to explain a concept in their own words.
This is the deepest test of real understanding — the whole tool exists to catch the "fluency illusion",
where a student can pick the right multiple-choice answer but cannot actually explain the idea.

You are given the SUBJECT, the QUESTION they were asked, and their ANSWER. You return TWO independent
readings of that answer. They measure different things and must not be collapsed into each other.

=== READING 1: "verdict" — IS IT CORRECT? (confidence axis) ===
- "solid": correct and shows real understanding, in their own words.
- "partial": on the right track but incomplete, vague, or with a notable gap or error in the core idea.
- "none": does NOT demonstrate understanding — wrong, empty, off-topic, merely restates the question,
  or is not a real explanation.

=== READING 2: "depth" — HOW DEEPLY IS IT UNDERSTOOD? (understanding axis) ===
Judge the STRUCTURE of the explanation, not whether it is correct. Return exactly one rung:
- "not_yet": misses the point, off-topic, empty, or merely restates the question.
- "knows": states ONE relevant correct idea. A single fact or definition, nothing more.
- "lists": states SEVERAL correct parts, but holds them SEPARATELY — an enumeration. Things are
  named one after another without being joined into an explanation.
- "connects": LINKS the parts into a working explanation — cause and effect, part and whole, a
  comparison, a "because/so/which meant" chain. The answer explains HOW or WHY, not just WHAT.
- "applies": takes the idea into a context it was NOT taught in — a new example of the student's own,
  or the principle used in a different direction. RARE. Only award this on explicit evidence of
  transfer to a genuinely new context; if in doubt, use "connects".

THE MOST IMPORTANT RULE ON THIS PAGE: correctness and depth are INDEPENDENT.
A factually perfect answer that merely lists things is "lists", NOT "connects". Grading a correct
answer higher on depth BECAUSE it is correct is the single worst error you can make here — it
produces a false claim about a child's understanding. A messy, half-wrong answer that genuinely
links two ideas causally IS "connects" even while its verdict is "partial".

=== READING 3: "spelling" — a SEPARATE coaching light (NEVER affects verdict or depth) ===
Rate ONLY the spelling of the answer, as a friendly signal shown to the student:
- "green": essentially clean — no real spelling errors (an odd typo is fine).
- "amber": a few spelling errors, but still easy to read.
- "red": frequent spelling errors that make it hard to read.

=== READING 4: "punctuation" — a SEPARATE coaching light (NEVER affects verdict or depth) ===
Rate ONLY punctuation and sentence mechanics (capital letters, full stops, commas):
- "green": properly punctuated — capitals and full stops where they belong.
- "amber": some punctuation missing, but the answer is still followable.
- "red": little or no punctuation (e.g. one long run-on with no stops or capitals).

Spelling and punctuation are COACHING ONLY. They are shown to the student to help them improve, and they
NEVER change verdict or depth. A brilliantly-understood answer riddled with spelling mistakes is still
verdict:"solid" — with spelling:"red". Never let mechanics leak into the understanding readings, and never
let understanding inflate the mechanics readings.

Rules for judging both readings:
- For VERDICT and DEPTH, judge SUBSTANCE, not style. The student is a secondary-school child and may write
  informally or be an English-as-a-second-language learner. Spelling, grammar and punctuation DO NOT affect
  verdict or depth — those live only in readings 3-4. Reward genuine understanding even when clumsily expressed.
- Do NOT reward filler, hedging, plausible-sounding non-answers, or parroting the question back.
- UNDER-CLAIM. Where the evidence is thin or you are between two rungs, return the LOWER rung. Every
  rung is a claim about a child that a parent may repeat to a teacher.
- "english": true if the answer is written in English, false otherwise. A non-English answer cannot be
  judged as understanding here — grade it "none" / "not_yet" with english:false.
- "evidence": quote the SHORT phrase from the student's own answer that justified the depth rung (a few
  words, verbatim), so the judgement is auditable. Empty string if the rung is "not_yet".

Output ONLY a JSON object, nothing else:
{"verdict": "solid" | "partial" | "none", "depth": "not_yet" | "knows" | "lists" | "connects" | "applies",
 "spelling": "green" | "amber" | "red", "punctuation": "green" | "amber" | "red",
 "english": true | false, "evidence": "short quote from the answer", "reason": "one short sentence"}`;

const MODEL = "claude-sonnet-5";

const CORS: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function light(v: unknown): string {
  const x = String(v ?? "").trim().toLowerCase();
  return (x === "green" || x === "amber" || x === "red") ? x : "green";
}
function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: { ...CORS, "content-type": "application/json" } });
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "POST") return json({ error: "method not allowed" }, 405);
  try {
    const { subject, question, answer } = await req.json();
    if (!answer || String(answer).trim().length < 1) return json({ error: "empty answer" }, 400);

    const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
    if (!apiKey) return json({ error: "grader not configured" }, 500);

    const user = `SUBJECT: ${subject ?? ""}\n\nQUESTION:\n${question ?? ""}\n\nSTUDENT'S ANSWER:\n${answer}\n\nGrade the answer. Output only the JSON verdict.`;

    const resp = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "x-api-key": apiKey, "anthropic-version": "2023-06-01", "content-type": "application/json" },
      body: JSON.stringify({ model: MODEL, max_tokens: 400, system: SYSTEM, messages: [{ role: "user", content: user }] }),
    });
    if (!resp.ok) return json({ error: "grader upstream error" }, 502);

    const data = await resp.json();
    const text = (data.content ?? []).filter((b: { type: string }) => b.type === "text").map((b: { text: string }) => b.text).join("");
    let grade: Record<string, unknown> = {};
    try { grade = JSON.parse(text.replace(/^```(?:json)?|```$/gm, "").trim()); } catch { grade = {}; }

    const v = String(grade.verdict ?? "").toLowerCase();
    const verdict = ["solid", "partial", "none"].includes(v) ? v : "partial";
    return json({
      verdict,                              // accuracy light: solid=green, partial=amber, none=red
      depth: grade.depth ?? null,
      spelling: light(grade.spelling),      // coaching only — never affects mastery
      punctuation: light(grade.punctuation),
      reason: String(grade.reason ?? "").slice(0, 200),
    });
  } catch (e) {
    return json({ error: String(e) }, 500);
  }
});
