#!/usr/bin/env python3
"""Generate the Supabase Edge Function for live teach-back grading FROM the Python grader's prompt,
so the instant display and the nightly (authoritative) grader can never drift. Re-run after editing
grade_teachback.SYSTEM:  python3 tools/gen_edge_function.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import grade_teachback as g

# Embed the Python SYSTEM prompt verbatim as a JS template literal (escape ` \ and ${).
esc = g.SYSTEM.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")

TS = '''// Supabase Edge Function — LIVE teach-back grader (grade-teachback).
// GENERATED by tools/gen_edge_function.py from tools/grade_teachback.py — DO NOT EDIT BY HAND.
// The quiz shell calls this on teach-back submit to show instant accuracy/spelling/punctuation lights.
// SECURITY: the ANTHROPIC_API_KEY lives here (Supabase secret) — a public page must never carry it.
// The nightly Python grader stays authoritative for the mastery ledger; this drives the instant display,
// and because both use the same prompt the lights the kid sees match the mastery signal.

const SYSTEM = `%s`;

const MODEL = "%s";

const CORS: Record<string, string> = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function light(v: unknown): string {
  const x = String(v ?? "").trim().toLowerCase();
  return (x === "green" || x === "amber" || x === "red") ? x : "green";
}
function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: { ...CORS, "content-type": "application/json" } });
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "POST") return json({ error: "method not allowed" }, 405);
  try {
    const { subject, question, answer } = await req.json();
    if (!answer || String(answer).trim().length < 1) return json({ error: "empty answer" }, 400);

    const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
    if (!apiKey) return json({ error: "grader not configured" }, 500);

    const user = `SUBJECT: ${subject ?? ""}\\n\\nQUESTION:\\n${question ?? ""}\\n\\nSTUDENT'S ANSWER:\\n${answer}\\n\\nGrade the answer. Output only the JSON verdict.`;

    const resp = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "x-api-key": apiKey, "anthropic-version": "2023-06-01", "content-type": "application/json" },
      body: JSON.stringify({ model: MODEL, max_tokens: 400, system: SYSTEM, messages: [{ role: "user", content: user }] }),
    });
    if (!resp.ok) return json({ error: "grader upstream error" }, 502);

    const data = await resp.json();
    const text = (data.content ?? []).filter((b: { type: string }) => b.type === "text").map((b: { text: string }) => b.text).join("");
    let grade: Record<string, unknown> = {};
    try { grade = JSON.parse(text.replace(/^```(?:json)?|```$/gm, "").trim()); } catch { grade = {}; }

    const v = String(grade.verdict ?? "").toLowerCase();
    const verdict = ["solid", "partial", "none"].includes(v) ? v : "partial";
    return json({
      verdict,                              // accuracy light: solid=green, partial=amber, none=red
      depth: grade.depth ?? null,
      spelling: light(grade.spelling),      // coaching only — never affects mastery
      punctuation: light(grade.punctuation),
      reason: String(grade.reason ?? "").slice(0, 200),
    });
  } catch (e) {
    return json({ error: String(e) }, 500);
  }
});
''' % (esc, g.DEFAULT_MODEL)

out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "supabase/functions/grade-teachback/index.ts")
open(out, "w").write(TS)
print("wrote", out, "(%d bytes)" % len(TS))
print("embeds verdict rungs:", "\"solid\"" in TS or "solid" in TS)
print("embeds spelling reading:", "READING 3" in TS)
print("embeds punctuation reading:", "READING 4" in TS)
